[input]
repeat_delay = 300
repeat_rate = 40
confine_pointer = false
main_sens = 1.0
alt_sens = 1.0
# TODO: language

[appearance]
background_color = '#000000'
lock_color = '#00000099'
cursor_theme = "" # can be left empty / deleted
cursor_size = 24 # can be deleted
ninb_opacity = 0.8
ninb_location = "right" # topleft, top, topright, left, right, bottomleft, bottomright

[wall]
wall_width = 2
wall_height = 3
stretch_width = 960
stretch_height = 360
alt_width = 1920
alt_height = 16384
use_f1 = false
remain_in_background = true

[reset]
unlock_behavior = "reset" # unlock, remain_locked, reset
count_resets = false
resets_file = "/home/user/resets.txt"
wall_bypass = false
grace_period = 100

# CPU weight for each instance group. Can be [1, 10000]. Delete any or all of these values to
# disable this.
[performance]
idle_cpu = 5
low_cpu = 20
high_cpu = 100
active_cpu = 500
preview_threshold = 30

[keybinds]
"Ctrl-Shift-D"      = ["wall_reset_all", "ingame_reset"]
"LMB"               = ["wall_reset"]
"Shift-LMB"         = ["wall_play"]
"Ctrl-LMB"          = ["wall_lock"]
"Ctrl-Shift-LMB"    = ["wall_focus_reset"]
"H"                 = ["alt_res"]
"K"                 = ["toggle_ninb"]
